stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker

test:
  stage: test
  script:
    - docker-compose up -d
    - sleep 60
    - curl -GET http://localhost/ || (echo "Frontend test failed" && exit 1)
    - curl -GET http://localhost/cat_get || (echo "Backend test failed" && exit 1)
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - master
  tags:
    - docker
